# Generated by Django 5.0.6 on 2024-05-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('UserMail', models.CharField(max_length=250)),
                ('UserPass', models.CharField(max_length=7)),
                ('IsAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
