# Generated by Django 5.0.6 on 2024-05-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='IsAdmin',
        ),
        migrations.AddField(
            model_name='user',
            name='UserRole',
            field=models.CharField(choices=[('admin', 'admin'), ('reader', 'reader')], default='reader', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserMail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserPass',
            field=models.CharField(max_length=128),
        ),
    ]
